# Generated by Django 3.2.25 on 2024-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_category', models.CharField(max_length=255, verbose_name='API类别')),
                ('api_name', models.CharField(max_length=255, verbose_name='API名称')),
                ('request_count', models.IntegerField(default=0, verbose_name='请求次数')),
            ],
            options={
                'verbose_name': 'API请求次数',
                'verbose_name_plural': 'API请求次数',
                'unique_together': {('api_name', 'api_category')},
            },
        ),
    ]
