# Generated by Django 3.2.25 on 2024-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('category', models.CharField(max_length=100, verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '面试题',
                'verbose_name_plural': '面试题',
            },
        ),
    ]
